<template>
  <header class="header"><a href="/" class="header__logo"><span class="header__logo-mark">M</span>Design System</a><nav class="header__nav"><a href="/" class="header__nav-link">Foundations</a><a href="/documentation/tabs.html" class="header__nav-link is-active">Components</a></nav></header>
  <div class="layout">
    <nav class="layout__nav"><div class="nav"><section class="nav__section"><span class="nav__section-title">Components</span><ul class="nav__list"><li class="nav__item"><a href="/documentation/button.html" class="nav__link">Button</a></li><li class="nav__item"><a href="/documentation/toggle.html" class="nav__link">Toggle</a></li><li class="nav__item"><a href="/documentation/checkbox.html" class="nav__link">Checkbox</a></li><li class="nav__item"><a href="/documentation/input.html" class="nav__link">Input</a></li><li class="nav__item"><a href="/documentation/select.html" class="nav__link">Select</a></li><li class="nav__item"><a href="/documentation/radio.html" class="nav__link">Radio</a></li><li class="nav__item"><a href="/documentation/textarea.html" class="nav__link">Textarea</a></li><li class="nav__item"><a href="/documentation/tabs.html" class="nav__link is-active">Tabs</a></li></ul></section></div></nav>
    <main class="layout__content"><article class="content"><span class="content__eyebrow">Components</span><h1>Tabs</h1><p class="content__lead">Tabs and TabsSimple switch between related content panes inside the same page context.</p>
      <h2 id="purpose" class="comp-section-h2">Purpose &amp; when to use</h2><ul><li>Use for segmented content views.</li><li>Do not use as page navigation replacement.</li></ul>
      <h2 id="anatomy" class="comp-section-h2">Anatomy &amp; sizing</h2><table class="props-table"><thead><tr><th>Property</th><th>Token</th><th>Value</th></tr></thead><tbody><tr class="props-row__meta"><td>Tabs padding</td><td><code>--marks-spacing-20 / --marks-spacing-24</code></td><td>20px 24px</td></tr><tr class="props-row__meta"><td>Tabs radius</td><td><code>--marks-radius-8</code></td><td>Top corners</td></tr><tr class="props-row__meta"><td>TabsSimple padding</td><td><code>--marks-spacing-12 / --marks-spacing-24</code></td><td>12px 24px</td></tr></tbody></table>
      <h2 id="variants" class="comp-section-h2">Variants &amp; all states</h2><div class="comp-demo"><div class="comp-demo__group" style="width:100%;"><span class="comp-demo__group-label">Tabs</span><Tabs v-model="tabA" :tabs="tabsA" /></div><div class="comp-demo__group" style="width:100%;"><span class="comp-demo__group-label">TabsSimple</span><TabsSimple v-model="tabB" :tabs="tabsB" /></div></div>
      <h2 id="behavior" class="comp-section-h2">Behavior rules</h2><ul><li>Clicking enabled item emits <code>update:modelValue</code> and <code>change</code>.</li><li>Disabled tab cannot be activated.</li></ul>
      <h2 id="content" class="comp-section-h2">Content rules</h2><ul><li>Use concise tab labels (1-2 words).</li><li>Keep peers parallel (Overview, Pricing, Availability).</li></ul>
      <h2 id="accessibility" class="comp-section-h2">Accessibility</h2><ul><li>Buttons are keyboard focusable by default.</li><li>Disabled state uses native disabled button behavior.</li></ul>
      <h2 id="examples" class="comp-section-h2">Examples &amp; anti-patterns</h2><div class="comp-demo"><div class="comp-demo__group" style="width:100%;"><span class="comp-demo__group-label">Do</span><TabsSimple v-model="good" :tabs="tabsB" /></div><div class="comp-demo__group" style="width:100%;"><span class="comp-demo__group-label" style="color:#FD3860;">Don't</span><TabsSimple v-model="bad" :tabs="badTabs" /></div></div>
      <h2 id="api" class="comp-section-h2">API / Props</h2><table class="props-table"><thead><tr><th>Name</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody><tr class="props-row__meta"><td><code>modelValue</code></td><td><code>String | Number</code></td><td><code>null</code></td><td>Selected value.</td></tr><tr class="props-row__meta"><td><code>tabs</code></td><td><code>Array</code></td><td><code>required</code></td><td>Items with <code>{label, value, disabled?}</code>.</td></tr></tbody></table>
      <h2 id="theming" class="comp-section-h2">Theming &amp; dark mode</h2><div class="comp-demo dark-preview"><div class="comp-demo__group" style="width:100%;"><TabsSimple v-model="theme" :tabs="tabsB" /></div></div>
    </article></main>
    <aside class="layout__aside"><div class="aside"><div class="aside__block aside__block--code"><div class="code-pane is-active"><pre><span class="token-keyword">import</span> TabsSimple <span class="token-keyword">from</span> <span class="token-string">'../../components/TabsSimple.vue'</span>
<span class="token-tag">&lt;TabsSimple</span> <span class="token-attr">v-model</span>=<span class="token-string">"activeTab"</span> <span class="token-attr">:tabs</span>=<span class="token-string">"tabs"</span> <span class="token-tag">/&gt;</span></pre></div></div></div></aside>
  </div>
</template>
<script>
export default { name: 'TabsDocPage', data() { return { tabA:'overview', tabB:'overview', good:'overview', bad:'x', theme:'overview', tabsA:[{label:'Overview',value:'overview'},{label:'Pricing',value:'pricing'},{label:'Availability',value:'availability',disabled:true}], tabsB:[{label:'Overview',value:'overview'},{label:'Pricing',value:'pricing'},{label:'Availability',value:'availability'}], badTabs:[{label:'Very long tab name that should not be used here',value:'x'},{label:'Another long one',value:'y'}] } } }
</script>
<style>@import '../../docs/reference-main.css';</style>
<style scoped>
.dark-preview { background:#000;border-color:#6F6F6F; --marks-color-primary-solid:#0E5842;--marks-color-primary-light:#032F22;--marks-color-red-100:#FFE4E9;--marks-color-red-200:#FD3860;--marks-color-red-300:#97001E;--marks-color-blue-100:#D7E7FF;--marks-color-blue-200:#2576F7;--marks-color-blue-300:#050D3A;--marks-color-green-100:#C0F3E4;--marks-color-green-200:#0FAF80;--marks-color-green-300:#0E5842;--marks-color-orange-100:#FFEBD2;--marks-color-orange-200:#FF8C00;--marks-color-orange-300:#854900;--marks-color-gray-100:#2A2A2A;--marks-color-gray-150:#505050;--marks-color-gray-200:#6F6F6F;--marks-color-gray-300:#8D8D8D;--marks-color-gray-350:#D1D1D1;--marks-color-gray-400:#ECECEC;--marks-color-gray-500:#FAFAFA;--marks-color-white:#000;--marks-color-black:#FFF; }
</style>
