<template>
  <header class="header"><a href="/" class="header__logo"><span class="header__logo-mark">M</span>Design System</a><nav class="header__nav"><a href="/" class="header__nav-link">Foundations</a><a href="/documentation/textarea.html" class="header__nav-link is-active">Components</a></nav></header>
  <div class="layout">
    <nav class="layout__nav"><div class="nav"><section class="nav__section"><span class="nav__section-title">Components</span><ul class="nav__list"><li class="nav__item"><a href="/documentation/button.html" class="nav__link">Button</a></li><li class="nav__item"><a href="/documentation/toggle.html" class="nav__link">Toggle</a></li><li class="nav__item"><a href="/documentation/checkbox.html" class="nav__link">Checkbox</a></li><li class="nav__item"><a href="/documentation/input.html" class="nav__link">Input</a></li><li class="nav__item"><a href="/documentation/select.html" class="nav__link">Select</a></li><li class="nav__item"><a href="/documentation/radio.html" class="nav__link">Radio</a></li><li class="nav__item"><a href="/documentation/textarea.html" class="nav__link is-active">Textarea</a></li><li class="nav__item"><a href="/documentation/tabs.html" class="nav__link">Tabs</a></li></ul></section></div></nav>
    <main class="layout__content"><article class="content"><span class="content__eyebrow">Components</span><h1>Textarea</h1><p class="content__lead">Textarea captures multi-line content with label, optional right-label, error state, and character count.</p>
      <h2 id="purpose" class="comp-section-h2">Purpose &amp; when to use</h2><ul><li>Use for paragraphs and notes.</li><li>Use Input for short single-line fields.</li></ul>
      <h2 id="anatomy" class="comp-section-h2">Anatomy &amp; sizing</h2><table class="props-table"><thead><tr><th>Property</th><th>Token</th><th>Value</th></tr></thead><tbody><tr class="props-row__meta"><td>Wrapper min-height</td><td><code>—</code></td><td>160px</td></tr><tr class="props-row__meta"><td>Textarea padding</td><td><code>--marks-spacing-16 / --marks-spacing-20</code></td><td>16px 20px</td></tr><tr class="props-row__meta"><td>Radius</td><td><code>--marks-radius-12</code></td><td>12px</td></tr></tbody></table>
      <div class="comp-demo"><div class="comp-demo__group" style="width:100%;max-width:560px;"><span class="comp-demo__group-label">Default</span><Textarea v-model="value" label="Notes" placeholder="Add notes" :max-length="250" /></div></div>
      <h2 id="variants" class="comp-section-h2">Variants &amp; all states</h2><table class="variant-table"><thead><tr><th></th><th>Default</th><th>Error</th><th>Disabled</th></tr></thead><tbody><tr><td><span class="state-chip state-chip--default">Default</span></td><td><Textarea v-model="vDefault" label="Notes" /></td><td><Textarea v-model="vError" label="Notes" :error="true" /></td><td><Textarea v-model="vDisabled" label="Notes" :disabled="true" /></td></tr><tr><td><span class="state-chip state-chip--hover">Hover</span></td><td><div class="force-hover"><Textarea v-model="vDefault" label="Notes" /></div></td><td><div class="force-hover"><Textarea v-model="vError" label="Notes" :error="true" /></div></td><td><Textarea v-model="vDisabled" label="Notes" :disabled="true" /></td></tr><tr><td><span class="state-chip state-chip--pressed">Clicked</span></td><td><div class="force-active"><Textarea v-model="vDefault" label="Notes" /></div></td><td><div class="force-active"><Textarea v-model="vError" label="Notes" :error="true" /></div></td><td><Textarea v-model="vDisabled" label="Notes" :disabled="true" /></td></tr></tbody></table>
      <h2 id="behavior" class="comp-section-h2">Behavior rules</h2><ul><li>Wrapper click focuses textarea.</li><li>Emits update/input/focus/blur events.</li><li>Character count mirrors current model length.</li></ul>
      <h2 id="content" class="comp-section-h2">Content rules</h2><ul><li>Label should describe expected content.</li><li>Placeholder is guidance, not validation text.</li></ul>
      <h2 id="accessibility" class="comp-section-h2">Accessibility</h2><ul><li>Native textarea keyboard behavior.</li><li>Label and control linked via generated id.</li></ul>
      <h2 id="examples" class="comp-section-h2">Examples &amp; anti-patterns</h2><div class="comp-demo"><div class="comp-demo__group" style="width:100%;max-width:560px;"><span class="comp-demo__group-label">Do</span><Textarea v-model="good" label="Special requests" placeholder="Tell us what we should know" /></div><div class="comp-demo__group" style="width:100%;max-width:560px;"><span class="comp-demo__group-label" style="color:#FD3860;">Don't</span><Textarea v-model="bad" placeholder="Type" /></div></div>
      <h2 id="api" class="comp-section-h2">API / Props</h2><table class="props-table"><thead><tr><th>Name</th><th>Type</th><th>Default</th><th>Description</th></tr></thead><tbody><tr class="props-row__meta"><td><code>modelValue</code></td><td><code>String | Number</code></td><td><code>''</code></td><td>Textarea content.</td></tr><tr class="props-row__meta"><td><code>rows</code></td><td><code>Number</code></td><td><code>6</code></td><td>Visible row count.</td></tr><tr class="props-row__meta"><td><code>label</code></td><td><code>String</code></td><td><code>null</code></td><td>Left label.</td></tr><tr class="props-row__meta"><td><code>labelRight</code></td><td><code>String</code></td><td><code>null</code></td><td>Right label.</td></tr><tr class="props-row__meta"><td><code>disabled</code></td><td><code>Boolean</code></td><td><code>false</code></td><td>Disabled state.</td></tr><tr class="props-row__meta"><td><code>error</code></td><td><code>Boolean</code></td><td><code>false</code></td><td>Error style.</td></tr><tr class="props-row__meta"><td><code>maxLength</code></td><td><code>Number</code></td><td><code>null</code></td><td>Enables char count display.</td></tr></tbody></table>
      <h2 id="theming" class="comp-section-h2">Theming &amp; dark mode</h2><div class="comp-demo dark-preview"><div class="comp-demo__group" style="width:100%;max-width:560px;"><Textarea v-model="theme" label="Notes" placeholder="Dark preview" /></div></div>
    </article></main>
    <aside class="layout__aside"><div class="aside"><div class="aside__block aside__block--code"><div class="code-pane is-active"><pre><span class="token-keyword">import</span> Textarea <span class="token-keyword">from</span> <span class="token-string">'../../components/Textarea.vue'</span>
<span class="token-tag">&lt;Textarea</span> <span class="token-attr">v-model</span>=<span class="token-string">"notes"</span> <span class="token-attr">label</span>=<span class="token-string">"Notes"</span> <span class="token-tag">/&gt;</span></pre></div></div></div></aside>
  </div>
</template>
<script>
export default { name: 'TextareaDocPage', data() { return { value:'', vDefault:'', vError:'', vDisabled:'Read only notes', good:'', bad:'', theme:'' } } }
</script>
<style>
@import '../../docs/reference-main.css';
.force-hover .marks-textarea-field:not(.marks-textarea-field--disabled):not(:focus-within) { box-shadow: 0 0 0 1px var(--marks-color-gray-300) !important; }
.force-active .marks-textarea-field:not(.marks-textarea-field--disabled) { border-color: var(--marks-color-black) !important; box-shadow: 0 0 0 4px rgba(0,0,0,0.3), 0 0 0 1px var(--marks-color-black) !important; }
</style>
<style scoped>
.dark-preview { background:#000;border-color:#6F6F6F; --marks-color-primary-solid:#0E5842;--marks-color-primary-light:#032F22;--marks-color-red-100:#FFE4E9;--marks-color-red-200:#FD3860;--marks-color-red-300:#97001E;--marks-color-blue-100:#D7E7FF;--marks-color-blue-200:#2576F7;--marks-color-blue-300:#050D3A;--marks-color-green-100:#C0F3E4;--marks-color-green-200:#0FAF80;--marks-color-green-300:#0E5842;--marks-color-orange-100:#FFEBD2;--marks-color-orange-200:#FF8C00;--marks-color-orange-300:#854900;--marks-color-gray-100:#2A2A2A;--marks-color-gray-150:#505050;--marks-color-gray-200:#6F6F6F;--marks-color-gray-300:#8D8D8D;--marks-color-gray-350:#D1D1D1;--marks-color-gray-400:#ECECEC;--marks-color-gray-500:#FAFAFA;--marks-color-white:#000;--marks-color-black:#FFF; }
</style>
