import { createApp } from 'vue';
import ButtonPrimary from '../components/ButtonPrimary.vue';
import ButtonSecondary from '../components/ButtonSecondary.vue';
import ButtonLine from '../components/ButtonLine.vue';
import ButtonGhost from '../components/ButtonGhost.vue';
import Select from '../components/Select.vue';
import Input from '../components/Input.vue';
import Textarea from '../components/Textarea.vue';
import Toggle from '../components/Toggle.vue';
import Checkbox from '../components/Checkbox.vue';
import Radio from '../components/Radio.vue';
import Status from '../components/Status.vue';
import Alert from '../components/Alert.vue';
import BigSwitch from '../components/BigSwitch.vue';
import Booking from '../components/Booking.vue';
import BookingInCalendar from '../components/BookingInCalendar.vue';
import Breadcrumb from '../components/Breadcrumb.vue';
import Breadcrumbs from '../components/Breadcrumbs.vue';
import Calendar from '../components/Calendar.vue';
import CalendarDatepicker from '../components/CalendarDatepicker.vue';
import CalendarDay from '../components/CalendarDay.vue';
import CardWithCounter from '../components/CardWithCounter.vue';
import CheckboxWithLabel from '../components/CheckboxWithLabel.vue';
import Dropdown from '../components/Dropdown.vue';
import EmptyState from '../components/EmptyState.vue';
import HorizontalSwitch from '../components/HorizontalSwitch.vue';
import InputField from '../components/InputField.vue';
import InputMessage from '../components/InputMessage.vue';
import NavbarItem from '../components/NavbarItem.vue';
import NavbarSide from '../components/NavbarSide.vue';
import NotificationBadge from '../components/NotificationBadge.vue';
import NotificationDialog from '../components/NotificationDialog.vue';
import NotificationMessage from '../components/NotificationMessage.vue';
import Place from '../components/Place.vue';
import RadioWithLabel from '../components/RadioWithLabel.vue';
import SmallSwitch from '../components/SmallSwitch.vue';
import SmallSwitchOption from '../components/SmallSwitchOption.vue';
import Tab from '../components/Tab.vue';
import Tabs from '../components/Tabs.vue';
import TabSimple from '../components/TabSimple.vue';
import TabsSimple from '../components/TabsSimple.vue';
import Table from '../components/Table.vue';
import TextareaField from '../components/TextareaField.vue';
import ToggleWithLabel from '../components/ToggleWithLabel.vue';
import Tooltip from '../components/Tooltip.vue';
import WeekPricingDay from '../components/WeekPricingDay.vue';
import Widget from '../components/Widget.vue';
import ComparisonApp from './ComparisonApp.vue';

const app = createApp(ComparisonApp);

app.component('ButtonPrimary', ButtonPrimary);
app.component('ButtonSecondary', ButtonSecondary);
app.component('ButtonLine', ButtonLine);
app.component('ButtonGhost', ButtonGhost);
app.component('Select', Select);
app.component('Input', Input);
app.component('Textarea', Textarea);
app.component('Toggle', Toggle);
app.component('Checkbox', Checkbox);
app.component('Radio', Radio);
app.component('Status', Status);
app.component('Alert', Alert);
app.component('BigSwitch', BigSwitch);
app.component('Booking', Booking);
app.component('BookingInCalendar', BookingInCalendar);
app.component('Breadcrumb', Breadcrumb);
app.component('Breadcrumbs', Breadcrumbs);
app.component('Calendar', Calendar);
app.component('CalendarDatepicker', CalendarDatepicker);
app.component('CalendarDay', CalendarDay);
app.component('CardWithCounter', CardWithCounter);
app.component('CheckboxWithLabel', CheckboxWithLabel);
app.component('Dropdown', Dropdown);
app.component('EmptyState', EmptyState);
app.component('HorizontalSwitch', HorizontalSwitch);
app.component('InputField', InputField);
app.component('InputMessage', InputMessage);
app.component('NavbarItem', NavbarItem);
app.component('NavbarSide', NavbarSide);
app.component('NotificationBadge', NotificationBadge);
app.component('NotificationDialog', NotificationDialog);
app.component('NotificationMessage', NotificationMessage);
app.component('Place', Place);
app.component('RadioWithLabel', RadioWithLabel);
app.component('SmallSwitch', SmallSwitch);
app.component('SmallSwitchOption', SmallSwitchOption);
app.component('Tab', Tab);
app.component('Tabs', Tabs);
app.component('TabSimple', TabSimple);
app.component('TabsSimple', TabsSimple);
app.component('Table', Table);
app.component('TextareaField', TextareaField);
app.component('ToggleWithLabel', ToggleWithLabel);
app.component('Tooltip', Tooltip);
app.component('WeekPricingDay', WeekPricingDay);
app.component('Widget', Widget);

app.mount('#app');
